### ISSUE TITLE
How do I install this using Crowdstrike's container registry?

### ISSUE THREAD

**Issue by haruiswaifu** [CrowdStrike/falcon-helm#104]
Hi,

I've read the readme for this helm chart here: https://artifacthub.io/packages/helm/falcon-helm/falcon-sensor

However, it's unclear to me how I can pull the container image(s) required from Crowdstrike's container registry.

If I run this command:

```
helm upgrade --install falcon-helm crowdstrike/falcon-sensor \
    -n falcon-system --create-namespace \
    --set falcon.cid="<CrowdStrike_CID>" \
    --set node.image.repository="registry.crowdstrike.com/falcon-node-sensor"
```

the pods will fail to pull the image.

Is there something I'm doing wrong here?

**Comment by christidis** [comment]
Hi,

You have to build your own image and host it on your private Docker Registry.
From [README's Deployment Considerations](https://github.com/CrowdStrike/falcon-helm/blob/main/README.md#deployment-considerations):

>_See https://github.com/CrowdStrike/Dockerfiles as an example of how to build a Falcon sensor for your registry._

**Comment by redhatrises** [comment]
Building with the docker files is no longer supported. Please see https://falcon.crowdstrike.com/documentation/20/falcon-sensor-for-linux#deploying-falcon-sensor-for-linux-as-a-daemon-set-on-a-kubernetes-cluster

**Comment by redhatrises** [comment]
Closing. Please reopen if more discussion is needed.

**Comment by nickperkins** [comment]
You can't run the sensor as a daemonset without having Crowdstrike Cloud Licenses. You'd need to look at starting it as part of the userdata of the node instance. It's a shame as it seems to have been possible previously with the self-built docker images.
