### ISSUE TITLE
[Request] Support Injection in certain Namespaces or all Namespaces with Authentication

### ISSUE THREAD

**Issue by byangtri** [CrowdStrike/falcon-helm#108]
**Request:**
Have a wildcard to target docker config secret in every namespace in cluster, or only allow falcon sensor injection in target namespace

**Problem you're trying to solve. What are you trying to do, and why is it hard?:**
Currently we have lots of namespaces in our cluster (20+ namespaces), and we are using the registry.crowdstrike.com/falcon-container/us-2/release/falcon-sensor Docker image which requires authentication. It is an inconvenience that we have to manually add in each namespace one-by-one into the `container.image.pullSecrets.namespaces` value or else our pods will not run as CS is injected to every pod in our cluster and fails to pull the image.

**Comment by TomRyan-321** [comment]
Hey @byangtri 

We'd strongly suggest you mirror the container image to a local registry, we only recommend pulling directly from the crowdstrike registry in non-production environments when customers are first trialing falcon container. Mirroring to a local registry ensures availability in the event of any network/internet outages or if for some reason the crowdstrike registry was unavailable for a period of time.

In terms of managing pullsecrets, this is a rather common problem within kubernetes. However there are some open source solutions you could look at to help manage this if you want a more global approach to cover new namespaces as well.

https://github.com/zakkg3/ClusterSecret
https://github.com/titansoft-pte-ltd/imagepullsecret-patcher
