### ISSUE TITLE
[Bug]: Release pipeline not running?

### ISSUE THREAD

**Issue by byangtri** [CrowdStrike/falcon-helm#120]
**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Crowdstrike Helm chart is running 1.14.0 and I see in latest code that the version should be 1.15.2
https://github.com/CrowdStrike/falcon-helm/commit/94e5e36a9928377347d19120ba82a6254004b8c0

The index.yaml also has not been updated in 18 days, hence still running old helm chart version https://github.com/CrowdStrike/falcon-helm/blob/gh-pages/index.yaml

**Attachments**
![image](https://user-images.githubusercontent.com/77506625/164069856-e4445ba3-bf75-4c77-b7f1-c2d9cce1a5c5.png)

@redhatrises @isimluk

**Comment by redhatrises** [comment]
Hello @byangtri ,

This is intentional in that the release pipeline won't run until we create a GH release. We don't do a per Chart version change release.

**Comment by byangtri** [comment]
Thanks, got it
