### ISSUE TITLE
Cast to int of kubeversion minor fails in k8s cloud distributions

### ISSUE THREAD

**Issue by lomluca** [CrowdStrike/falcon-helm#130]
In many points, the chart checks the k8s minor version, in order to render different pieces of yaml.
The logic relies on `int .Capabilities.KubeVersion.Minor` that doesn't work properly for Kubernetes distribution of cloud providers. The reason behind that is the presence of a "+" character as suffix in the minor string.

Here are many examples for different versions of EKS cluster, the output of `kubectl version`:
```
# eks 1.20
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
 
# eks 1.21
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
 
# eks 1.22
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

In these cases, the resulting value is 0, breaking all the if/else logic in the chart.

Searching similar issues, I think the same thing happens on GKE, I cannot test it.

**Comment by redhatrises** [comment]
Hmmm... if semver isn't followed in the minor versioning which is unexpected, we should probably update to do semver comparison for kubeversion handling. https://helm.sh/docs/chart_template_guide/function_list/#semantic-version-functions

**Comment by domdepasquale** [comment]
Something like

`{{- if (semverCompare "<1.22" .Capabilities.KubeVersion.Version) }}`

instead of 

`{{- if lt (int (semver .Capabilities.KubeVersion.Version).Minor) 22 }}`

@redhatrises ?

**Comment by redhatrises** [comment]
I was originally thinking that we should use `semverCompare`, but I am good with `semver`. We can always update later.
