### ISSUE TITLE
DaemonSet creates directory in /opt which is read-only in Google COS

### ISSUE THREAD

**Issue by hazcod** [CrowdStrike/falcon-helm#159]
Hi,

The daemonset [here](https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/templates/daemonset.yaml#L89) creates a directory in `/opt/Crowdstrike` to persist the AID across container restarts.

This directory however is kept as read-only on cos_containerd nodes in GKE on GCP, which disallows the use of Falcon as a node sensor.
Would it be possible to either move this to a universal location (e.g. `/home/` is writeable) or make this configurable?

Ref: https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem

**Comment by isimluk** [comment]
Hello @hazcod,

Thank You for taking the time to reach us and file the issue. I am sorry to report that Google COS is currently not supported by the NodeSensor. We recommend you evaluate sister product called Falcon Container sensor. Falcon Container sensor while comparable in capabilities differs in architecture and thus allows for deployment in platforms like GKE Autopilot or EKS Fargate.

**Comment by hazcod** [comment]
Hi @isimluk , sadly the container sensor is very expensive since it licenses per Pod.
The Node sensor makes more sense since it's counted per server.
So IMO this minor change would allow for a far more cost effective deployment.

**Comment by redhatrises** [comment]
> Hi @isimluk , sadly the container sensor is very expensive since it licenses per Pod. The Node sensor makes more sense since it's counted per server. So IMO this minor change would allow for a far more cost effective deployment. cos_containerd -is- mentioned as supported in the docs.

For the container sensor, yes it is supported. For the node sensor, it is not supported. There are more changes needed vs just writing to a directory that is not /opt. As the node sensor is a kernel module, it would need to be signed, etc. There is a long term plan to fix this in the works. It would be best to open a ticket with CS support to address the supportability of sensors for GCOS.

**Comment by hazcod** [comment]
I'll await the eBPF sensor then, thank you.
