### ISSUE TITLE
Enable resource requests/limits on daemonset pods

### ISSUE THREAD

**Issue by jcogilvie** [CrowdStrike/falcon-helm#173]
Please enable me to set a resource request/limit on the daemonset pods.  

The structure already exists around the container injection variant, and I'd like the same on DS pods so that my cluster autoscaler can correctly understand how much space needs to be provisioned to fit one of the falcon pods.

When karpenter (our cluster autoscaler) detects unschedulable workloads, it provisions a new node to fit those workloads on it.

For example, if I have 2Gi of memory requests that the scheduler cannot fulfill, karpenter provisions an instance that provides (2Gi + daemonset requests) of memory. If the falcon sensor does not participate in this calculation, my nodes are undersized by whatever amount of resource utilization the falcon sensor would require, and either a daemonset pod is unschedulable (very bad) or a workload pod is unschedulable, causing me to create another instance which is then subject to the same problem again (also bad, but differently).

So I and others need to be able to specify the resource requests for all pods, daemonset or otherwise.

**Comment by Kulagin-G** [comment]
It's a really relevant request, I'm confused why PR was closed =(

**Comment by fradee** [comment]
Any updates for resources for daemonset mode?

**Comment by fradee** [comment]
@redhatrises already done - Case number 01097263.

**Comment by redhatrises** [comment]
FYI. Limits will probably never be supported.

**Comment by fradee** [comment]
A great solution for the great SW...

**Comment by matt-demers** [comment]
Our organization is trying to deploy this chart, but is going to have to manually copy and modify the chart because it doesn't support setting resource limits on the daemonset. This is a standard feature of most helm charts, so I don't understand why the MR was closed

**Comment by redhatrises** [comment]
Because we don't support setting limits especially since kernel processes aren't reported correctly back .e.g. `20MiB and the cpu usage has held constant at 200-300mcores` is quite inaccurate usage reporting back.
