### ISSUE TITLE
[falcon-sensor-cleanup] Discussion about the DeamonSet repetitive restarting mechanism

### ISSUE THREAD

**Issue by runlevel5** [CrowdStrike/falcon-helm#182]
To the team at CrowdStrike

I am writing to you in hope of creating a conversation on the design of falcon-sensor-cleanup deamonset. Here is a bit more context from my end, after deploying the helm chart to EKS, I noticed that there are failed falcon-sensor-cleanup pod with CrashLoopBackOff error status and high level of Pod restart count. Upon closer look, I realise this is just the design of the deamonset:

```
Init container: perform cleanup
Main container: sleep 10s
```

which is fine but it gives monitor application hard time to identify if the daemonset truly crash or not. In my case, it is likely that I have to implement some filters to avoid being flooded with bad health pods.

So I've been wondering instead of doing it that way, why don't we have a wrapper in the main falcon-sensor daemonset that would perform the same task.

**Comment by bigjimnolan** [comment]
I found this as well.  It looks like they put an extra 'host_' before the directory name in the jsonnet.  It's this file ->
```helm-charts/falcon-sensor/templates/node_cleanup.yaml:        args: ['-c', 'if [ -x "/opt/CrowdStrike/falcon-daemonset-init" ]; then echo "Running /opt/CrowdStrike/falcon-daemonset-init -u"; /opt/CrowdStrike/falcon-daemonset-init -u ; else rm -rf "/host_opt/CrowdStrike"; fi']
helm-charts/falcon-sensor/templates/node_cleanup.yaml:            mountPath: /host_opt
helm-charts/falcon-sensor/templates/daemonset.yaml:        args: ['-c', 'if [ -x "/opt/CrowdStrike/falcon-daemonset-init" ]; then echo "Running falcon-daemonset-init -i" ; /opt/CrowdStrike/falcon-daemonset-init -i ; else if [ -d "/host_opt/CrowdStrike/falconstore" ] ; then echo "Re-creating /opt/CrowdStrike/falconstore as it is a directory instead of a file"; rm -rf /host_opt/CrowdStrike/falconstore; fi; mkdir -p /host_opt/CrowdStrike && touch /host_opt/CrowdStrike/falconstore; fi']
helm-charts/falcon-sensor/templates/daemonset.yaml:            mountPath: /host_opt
C02ZR29WMD6R-16:falcon-helm jnolan$ vi helm-charts/falcon-sensor/templates/node_cleanup.yaml ```

the extra `host_` with the `rm -rf /host_opt/CrowStrike` is causing the problem.  I have no idea how to do a PR here, though :)

**Comment by redhatrises** [comment]
Unfortunately, a wrapper won't work for a couple of reasons:

1. The cleanup of sensor shouldn't happen unless the sensor is intended to be removed from the system permanently because the configuration files should still exist in the circumstance that the pod was killed and re-deployed.
2. Since the sensor process is running on the node, it could still write after a cleanup happened defeating the purpose.

Ultimately, the solution would be for k8s to have a PostStop lifecycle hook... but not sure if that will ever happen.
