### ISSUE TITLE
falcon-kac: hardcoded pods in ResourceQuota blocking falcon-kac deployment

### ISSUE THREAD

**Issue by dttung2905** [CrowdStrike/falcon-helm#241]
Hi team,

In the README doc, we have the example deployment in `falcon-kac` and this works perfectly fine.
```
  helm upgrade --install falcon-kac $KAC_HELM_REPO \
     -n falcon-kac --create-namespace \
     --set falcon.cid=$FALCON_CID \
     --set image.repository=$KAC_IMAGE_REPO \
     --set image.tag=$KAC_IMAGE_TAG
```

However, the problem arises when we deploy in other namespaces, for example `kube-system`. The hard limit of pods is hardcoded in ResourceQuota object which might prevent the new kac deployment to be spun up. The reason is because there are existing deployment with priority class `system-cluster-critical` like the API server, scheduler, and controller-manager
https://github.com/CrowdStrike/falcon-helm/blob/654dd90b111f06e9fd69b73545567937e1e5adac/helm-charts/falcon-kac/templates/resourcequota.yaml#L8-L16

The proposed solution would be to parameterise this value `spec.hard.pods` to values.yaml file and set a default value of 2 to maintain backward compatibility

**Comment by redhatrises** [comment]
Hello,

A couple of things.

1. The admission controller should only be deployed in its own namespace and not in namespaces with existing resources. Deploying in a namespace with existing resources is not a best practice.
2. There should not be multiple installs of the admission controller in the cluster.
