### ISSUE TITLE
Private Image Registry

### ISSUE THREAD

**Issue by ishworgurung** [CrowdStrike/falcon-helm#244]
We have a large number of EKS clusters and our deployments have test environments. To test Falcon sensor deployment as a proper deployment pipeline (think: ArgoCD/Tekton/Kluctl), this causes immediate friction and paper cuts. 

The documentation is full of _do this, then do that_ **by hand** which is an immediate smelly anti-pattern when you run a well-functioning DevOps culture.

So, my question is: Why does the Falcon sensor require a private authenticated registry? 

I understand the _when images get compromised_ angle but if significant portion of the time were spent living under the rock then check this out https://docs.sigstore.dev/#why-cryptographic-signing

**Comment by redhatrises** [comment]
I am not sure what the request is here. The is a helm chart-only repo. Anything w.r.t. the container images or the CS Falcon registry is out-of-scope of this repo.

> Why does the Falcon sensor require a private authenticated registry?

This is both a best practice as well as good security practice for containers and container registries. For EKS with the helm charts, you can easily configure the IAM annotation for ECR access or provide a pull secret token which would then be used as part of the pipeline.

**Comment by ishworgurung** [comment]
> This is both a best practice as well as good security practice for containers and container registries.

I understand fully in this context what is and isn't a good security hygiene.

I am talking about when one needs to _pull_ the image, the guideline is to ensure it is accessed from CrowdStrike's _private authenticated registry_. 

So, my question is: what is the reasoning behind making this registry private? why not cosign, SBOM and make it publicly accessible?

**Comment by redhatrises** [comment]
Besides the fact that the sensor is proprietary and the secondary legal requirement for it being in a private registry, Cosign (image verification) and SBOM (dependency list) don't address adversary and counter-adversary operations w.r.t. container images and security sensors.

Closing this issue as out-of-scope for this project. Please contact your CS account for a discussion on this.
