### ISSUE TITLE
Custom imagePullSecrets in "cs-k8s-protection-agent" helm chart

### ISSUE THREAD

**Issue by Tomer20** [CrowdStrike/falcon-helm#249]
Hi,

There are currently 2 issues with the `cs-k8s-protection-agent` helm chart for me:

## 1
When pulling the helm chart `cs-k8s-protection-agent` we get version `0.1647.0`, while in the `main` branch is `0.1474.0` ([Chart.yaml in main branch](https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/cs-k8s-protection-agent/Chart.yaml)). 

To reproduce:
1. `helm repo add kpagent-helm https://registry.crowdstrike.com/kpagent-helm`
2. `helm fetch cs-k8s-protection-agent`
3. Check `Chart.yaml` file.

## 2

As far as I can see, the `crowdstrikeConfig.dockerAPIToken` is a secret value.

In your `main` branch I can skip this when using `image.pullSecrets` property, however, in the pulled chart version I get (`0.1647.0`), this property does not exists.

---

Please note that I got the installation instructions from Crowdstrike's CSPM console, on the k8s integration setup page. You can see that the "helm repo add" command is a bit different from [this repo's readme](https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-kac/README.md#install-falcon-kubernetes-admission-controller).

What instructions should I use? What version?

**Comment by redhatrises** [comment]
I believe that both these issues are fixed.

Whenever there are differences between console and GH, it should be viewed in the upstream (GH) / downstream (console) context.
