### ISSUE TITLE
Falcon Image Analyzer helm chart does not use securityContext for deployment

### ISSUE THREAD

**Issue by aywrite** [CrowdStrike/falcon-helm#262]
The falcon image analyser allows configuration of a variable `securityContext`. This variable is used by the chart in the daemonset template but not in the deployment template, which means it is impossible to override the securityContext when using the deployment.

On a related note is it required/recommended to ran as user 0 by default? Is there a reason the default/hardcoded value isn't another user?

**Comment by redhatrises** [comment]
> On a related note is it required/recommended to ran as user 0 by default? Is there a reason the default/hardcoded value isn't another user?

This is actually required for Azure to read `azure.json`. It can probably be configured to non-root when not Azure which will probably be fixed in an upcoming release.
