### ISSUE TITLE
Allow for post-delete helm hook to be optionally disabled

### ISSUE THREAD

**Issue by congiv** [CrowdStrike/falcon-helm#278]
Running falcon-sensor in an environment where the nodes will be deleted at the same time as/prior to the uninstall of falcon-sensor. In this case, the post-delete hook will never be schedulable because there are no nodes and the uninstall will hang indefinitely.

It would be nice if there was an option to disable this hook, as in my case I will never be uninstalling the falcon-sensor in a case where I'm not also deleting the whole cluster and its nodes.

**Comment by redhatrises** [comment]
Please use `--no-hooks` for this.

**Comment by congiv** [comment]
@redhatrises I would, but I'm using ArgoCD where helm is only used as the templating engine. ArgoCD appears to have logic to translate a helm hook to the sequence during the uninstall.

For other similar use cases, I've only had success by toggling off the hook manifests that i don't need.

FYI: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks

**Comment by congiv** [comment]
I've opened a PR that addresses this, but keeps the default behavior that the hook is enabled. This way the general user can follow your recommendation around `--no-hooks` but gives users the flexibility to toggle off the manifests in use cases like mine where the `helm` bin isn't performing the uninstall, as with ArgoCD.

Thanks for your quick response and consideration, I really appreciate it!
