### ISSUE TITLE
Adding tags to deployment

### ISSUE THREAD

**Issue by chrishatfield86** [CrowdStrike/falcon-helm#28]
I'm installing falcon via helm and I need to add tags to my sensors.

The linux instructions state that you can add a `--tags` option to `falconctl`

e.g.

```/opt/CrowdStrike/falconctl --tags="Foo,Bar"```

There are a list of options in the falcon sensor dockerfile but none of them align to tags - https://github.com/CrowdStrike/Dockerfiles/blob/15116be9f58f8a4b7b60c1f322a821d7df499f1f/entrypoint.sh#L20

Is there a correct way of adding tags using this helm chart?

**Comment by chrishatfield86** [comment]
I figured it out. While tags isn't in the values file they are referenced in `questions.yaml`

You can add them like this:

```falcon:
  tags: "foo,bar"```

**Comment by redhatrises** [comment]
This looks to be a bug if the tags field is not in `values.yaml`. Reopening the ticket to make sure this is addressed and validated.
