### ISSUE TITLE
Command for daemonset not longer check if `/opt/CrowdStrike/falcon-daemonset-init` exists

### ISSUE THREAD

**Issue by vmignot** [CrowdStrike/falcon-helm#288]
Since the release of falcon-sensor 1.28.1, the command for the daemonset is not checking for the existence of the file `/opt/CrowdStrike/falcon-daemonset-init`.
See: https://github.com/CrowdStrike/falcon-helm/commit/018b26013e931d8943a3ecfd35b34a0bfc100cc0#diff-a7591ec8dc15465b3ed40d8112b4b27f8b98a084f4794117047a0c0f8cc2f39cL106

I'm building my own image using the binary `falcon-sensor-7.14.0-16703.amzn2023.x86_64.rpm`, and when installing it on a container, it does not create this file.

Can we either:
1. Go back to a command where the existence of the file is checked?
2. Create a parameter in the `values.yaml` that will allow to override the command?

Thanks!

**Comment by redhatrises** [comment]
Hello,

Thanks for opening this. Unfortunately, creating your own custom container with the sensor rpm is unsupported. Only the use of the official daemonset images from the crowdstrike registry with Falcon Cloud security is supported. It is now expected that this utility is used to handle filesystem reqs for the supported daemonset images. The rpm won't install this utility as the official CrowdStrike daemonset images are the only supported sensor for deployment. With this in mind, we won't be going to accommodate custom rpm installations considering they aren't supported.
