### ISSUE TITLE
falcon-sensor is unusable on GKE with COS_CONTAINERD nodes

### ISSUE THREAD

**Issue by mikesmitty** [CrowdStrike/falcon-helm#296]
Got a bit of a chicken-and-egg scenario on GKE COS_CONTAINERD nodes it looks like. As you're presumably already aware, `/opt` is read-only on COS_CONTAINERD nodes so the `falconstore` initContainer sets up a bind mount for `/opt/CrowdStrike` to `/var/CrowdStrike_bind`. The problem being, that initContainer's pod is unscheduleable on any new nodes because it depends on the hostPath mount in `/opt/CrowdStrike` already existing

**Comment by redhatrises** [comment]
Please make sure that you are using the latest sensor (7.15+), and the latest helm chart. The initContainer doesn't have a hostpath mount and shouldn't need it as the initContainer is meant to create and handle the bind mount as well as directory creation.

**Comment by mikesmitty** [comment]
Hey, thanks for responding. It must have been an issue with the 7.14 image I was using, it's working now.
