### ISSUE TITLE
Issue: Multi-architecture image of falcon-sensor fails on aarch64 nodes

### ISSUE THREAD

**Issue by sagnikundu** [CrowdStrike/falcon-helm#336]
Description: 
We are experiencing issues while deploying the multi-architecture image of falcon-sensor on clusters that have a mix of x86 and aarch64 instances. The falcon-sensor daemonset pods with the multi-architecture image successfully come up on nodes with x86 architecture but fail to start on nodes with aarch64 architecture.

Steps to Reproduce:

Deploy the falcon-sensor daemonset with the multi-architecture image tag 7.18.0-17106-1.falcon-linux.Release.US-1 on a cluster with mixed x86 and aarch64 nodes.

Observe the pod status on nodes with aarch64 architecture.

Expected Behavior: 
The falcon-sensor daemonset pods should start successfully on both x86 and aarch64 nodes.

Actual Behavior: 
The falcon-sensor daemonset pods start successfully on nodes with x86 architecture but fail to start on nodes with aarch64 architecture.

Pod Logs (aarch64):

$ kubectl logs -f falcon-helm-falcon-sensor-9phnl
exec /entrypoint.sh: exec format error

Pod Events:

Normal   Pulled   25s                kubelet  Successfully pulled image "231222121756.dkr.ecr.ap-southeast-2.amazonaws.com/falcon-sensor:7.18.0-17106-1.falcon-linux.Release.US-1" in 101.803005ms (101.818976ms including waiting)
Warning  BackOff  1s (x6 over 65s)   kubelet  Back-off restarting failed container falcon-node-sensor in pod falcon-helm-falcon-sensor-9phnl_falcon-system(8920e17e-b4aa-4bf3-8bed-09af504a23a7)
Environment:

Multi-arch Image tag used: 7.18.0-17106-1.falcon-linux.Release.US-1
Cluster with mixed x86 and aarch64 nodes

**Comment by gpontejos** [comment]
Thanks for reaching out. Multi-arch deployments of the sensor are not supported at this time: https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/README.md#dependencies

**Comment by sagnikundu** [comment]
Thanks @redhatrises , I used **skopeo** to copy over all the manifests to our ECR , for both the types and that fixed the issue. I was able to deploy falcon-sensor on the cluster having a mix of amd64(x86) and arm64 instances.
