### ISSUE TITLE
Enhance the Falcon Helm charts with Falcon Container

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/falcon-helm#44]
The Helm charts need to be able to deploy Falcon Container or the kernel sensor

**Comment by hazcod** [comment]
@redhatrises isn't that already the case? Or am I missing something here.
https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/values.yaml#L6

**Comment by redhatrises** [comment]
There is missing functionality to fully closing this. With the operator providing more functionality and ultimately the helm chart will be updated to deploy the operator, I continue to debate adding in all the missing components.

**Comment by redhatrises** [comment]
Closing this as a lot of remaining functionality has been added. See #103
