### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ax-tbowyer** [CrowdStrike/falcon-helm#55]
Hey Team,

Any plan to run the release webhook? There are some commits we really need like https://github.com/CrowdStrike/falcon-helm/commit/8d83c60f4d7f5245aa0b1a976dc763e8c9c16090#diff-a7591ec8dc15465b3ed40d8112b4b27f8b98a084f4794117047a0c0f8cc2f39c

**Comment by redhatrises** [comment]
Hello.

Thanks for opening a question around this! We should be creating a new release in the next few weeks. There are some additional changes that need to happen to the configmap and the daemonset in addition to the new content around the injector webhook.

**Comment by ax-tbowyer** [comment]
Thanks @redhatrises I'll close this for now
