### ISSUE TITLE
AWS EKS Support

### ISSUE THREAD

**Issue by thpham** [CrowdStrike/falcon-helm#78]
Hello,

Do this deployment support AWS EKS ? this is really much wanted, AWS is the global leader so I suppose a lot of people would be interested !

**Comment by redhatrises** [comment]
Hello,

EKS was supported several releases ago. Please see https://artifacthub.io/packages/helm/falcon-helm/falcon-sensor

**Comment by redhatrises** [comment]
The repo is now a collection of helm charts. To find the supported versions of kubernetes, you will now need to check the helm charts readme and not the main readme. In this case, the falcon sensor helm chart can be viewed by going to https://artifacthub.io/packages/helm/falcon-helm/falcon-sensor or https://github.com/CrowdStrike/falcon-helm/blob/main/helm-charts/falcon-sensor/README.md
