### ISSUE TITLE
init container issue 

### ISSUE THREAD

**Issue by henri9fr** [CrowdStrike/falcon-helm#79]
I have followed : https://crowdstrike.github.io/falcon-helm/ to install here are the command I use to install : 
helm repo add crowdstrike https://crowdstrike.github.io/falcon-helm 
helm upgrade --install falcon-helm crowdstrike/falcon-sensor \ 
  -n falcon-system --create-namespace \ 
  --set falcon.cid="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \ 
  --set node.image.repository="xxxxxx/xxxxxxxxxxxxxxxxx/falcon-sensor" 
  
I have uploaded the sensor in my container registry in GCP . the sensor downloaded is falcon-sensor-6.31.0-1409.container.x86_64.tar.bz2 ( Falcon Usermode Container Sensor", "platform": "linux", "os": "Container", "os_version")
 I'm using a GKE kubernetes cluster . 
 Can't start the container . deamon set stops at the init container : /bin/sh not found. 
 (only bin/bash available on the container) 
 If I edit the demon set it continue to fail because touch is missing . 
 if I replace the command touch by $null >> in the deamon set .. I get a not authorized error
 
 help will be appreciated

**Comment by redhatrises** [comment]
Thanks for the reply.

Since you are using the Falcon Container Sensor for deploying as a sidecar to your pods, you will want to run helm like so:

```
helm upgrade --install falcon-helm crowdstrike/falcon-sensor \
-n falcon-system --create-namespace \
--set falcon.cid="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \
--set node.enabled=false \
--set container.enabled=true \
--set container.image.repository="xxxxxx/xxxxxxxxxxxxxxxxx/falcon-sensor"
```

**Comment by henri9fr** [comment]
Thanks for your comment . 
I recreated my cluster to make sure that I was in the same conditions than the previous time 

I Ran: 
helm upgrade --install falcon-helm crowdstrike/falcon-sensor -n falcon-system --create-namespace --set falcon.cid="xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xx" --set node.enabled=false --set container.enabled=true --set container.image.repository="xxxxxx/falcon-sensor-gke"
Release "falcon-helm" does not exist. Installing it now.
NAME: falcon-helm
LAST DEPLOYED: Mon Nov  1 15:09:50 2021
NAMESPACE: falcon-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing the CrowdStrike Falcon Helm Chart!

Access to the Falcon Linux and Container Sensor downloads at https://falcon.crowdstrike.com/hosts/sensor-downloads are
required to complete the install of this Helm chart. This is provided automatically to all active CrowdStrike customers.
Additionally, a containerized sensor must be present in a container registry accessible from Kubernetes installation.
CrowdStrike Falcon sensors will deploy across all pods as sidecars in your Kubernetes cluster after
installing this Helm chart and starting a new pod deployment for all your applications.
The default image name to deploy the pod sensor is `falcon-sensor`.

An extremely common error on installation is accidentally forgetting to add your containerized
sensor to your local image registry prior to executing `helm install`.

That part done a quick check gives me : 

kubectl get po -n falcon-system
NAME                                     READY   STATUS             RESTARTS   AGE
falcon-sensor-injector-f48548479-m879n   0/1     CrashLoopBackOff   6          7m8s

 kubectl -n falcon-system  logs falcon-sensor-injector-f48548479-m879n --previous

time="2021-11-01T20:16:04Z" level=info msg="Starting Injector..."
time="2021-11-01T20:16:04Z" level=fatal msg="FALCON_INJECTOR_LISTEN_PORT not found"


Note :  I'm still using the falcon container : falcon-sensor-6.31.0-1409.container.x86_64.tar.bz2 , 1.20.10-gke.301, and Container-Optimized OS with Containerd (cos_containerd) for the nodes 

Thanks a lot in advance for your help

**Comment by redhatrises** [comment]
Thanks for reporting back. This should be fixed in the 1.4.0 release that was released today, so running the following should pull the updated helm chart.

```
$ helm repo update
```

**Comment by henri9fr** [comment]
hello , , so I ran the following  : 


_helm repo update_
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "crowdstrike" chart repository

Update Complete. ⎈Happy Helming!⎈

then 
_helm upgrade --install falcon-helm crowdstrike/falcon-sensor -n falcon-system --create-namespace --set falcon.cid="xxxxxxxxxxxxxxxxxxxxxxxxxxxx-xx" --set node.enabled=false --set container.enabled=true --set container.image.repository="xxxxxx/falcon-sensor-gke"_

Checking the deployment I can see I'm running the version 1.4.0 : 

_kubectl get deployment falcon-sensor-injector -n falcon-system -o yaml_
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: falcon-helm
    meta.helm.sh/release-namespace: falcon-system
  creationTimestamp: "2021-11-01T20:09:55Z"
  generation: 2
  labels:
    app: falcon-sensor-injector
    app.kubernetes.io/component: container_sensor
    app.kubernetes.io/instance: falcon-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: falcon-sensor
    crowdstrike.com/provider: crowdstrike
    helm.sh/chart: falcon-sensor-1.4.0

All showing green on the google console  ( workload and services) 

_kubectl logs falcon-sensor-injector-9d899b64d-zfc2m -n falcon-system_
time="2021-11-02T13:43:05Z" level=info msg="Starting Injector..."
time="2021-11-02T13:43:09Z" level=info msg="Starting HTTPS server" listen port=4433

Going to the next step ,  I scaled up my deployment 

_kubectl scale deployment proxy --replicas=3 -n squid;_

deployment.apps/proxy scaled

But unfortunately I'm stuck there : 
 Internal error occurred: failed calling webhook "falcon-sensor-injector.falcon-system.svc": Post "https://falcon-sensor-injector.falcon-system.svc:443/mutate?timeout=30s": context deadline exceeded

I have made sure the port 443 , 4433, are exposed on my proxy pods -- just in case 

Looks like the MutatingWebhookConfiguration  is setup as a service  and version is 1.4.0 

  _kubectl get MutatingWebhookConfiguration -n falcon-system_
NAME                                                 WEBHOOKS   AGE
falcon-sensor-injector                               1          18h
pod-ready.config.common-webhooks.networking.gke.io   1          18h


Name:         falcon-sensor-injector
Namespace:
Labels:       app=falcon-sensor
              app.kubernetes.io/component=container_sensor
              app.kubernetes.io/instance=falcon-helm
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=falcon-sensor
              crowdstrike.com/provider=crowdstrike
              helm.sh/chart=falcon-sensor-1.4.0
Annotations:  meta.helm.sh/release-name: falcon-helm
              meta.helm.sh/release-namespace: falcon-system

Thanks again in advance for your help

**Comment by henri9fr** [comment]
I got the webhook solved by opening a FW rule on port 4433 on my controlplane ! 
Thanks a lot for all the help

**Comment by redhatrises** [comment]
Yeah... if you are managing ports on the control plane itself. That makes sense about the denial. Is there some sort of enhancement we should do to the helm chart to handle this?

**Comment by henri9fr** [comment]
I'm not sure , perhaps I'm in a specific spot , using shared networks from an other project to manage proxy access .... I did not tested it in a more "classic" situation .  Now , having said that , could be good to have that FW rule opened automatically...

**Comment by redhatrises** [comment]
Is the FW a kubernetes solution or is it something else?

**Comment by henri9fr** [comment]
Firewall rule  is mandatory for me because of our way to implement , so I think that should not be part of the helm side, looks like i'm the only one yet to get that issue .

**Comment by shawndwells** [comment]
Some of the other container/EKS docs have sections around common misconfiguration or deployment errors. For example the line in our README...
`````
An extremely common error on installation is accidentally forgetting to add your containerized
sensor to your local image registry prior to executing helm install.
`````

What if we convert that to a h2/h3 section around common deployment issues, and document this edge case there? e.g.

"Some deployments may be using using custom/external firewall services. if that's the case, ensure port XYZ is opened otherwise you may receive an error similar to ``foo``"

**Comment by henri9fr** [comment]
I think it is a great idea  ,   and the webhook issue I got is a great sample for this kind of common deployement issue

**Comment by ardimaul** [comment]
> I have followed : https://crowdstrike.github.io/falcon-helm/ to install here are the command I use to install : helm repo add crowdstrike https://crowdstrike.github.io/falcon-helm helm upgrade --install falcon-helm crowdstrike/falcon-sensor \ -n falcon-system --create-namespace \ --set falcon.cid="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" \ --set node.image.repository="xxxxxx/xxxxxxxxxxxxxxxxx/falcon-sensor"
> 
> I have uploaded the sensor in my container registry in GCP . the sensor downloaded is falcon-sensor-6.31.0-1409.container.x86_64.tar.bz2 ( Falcon Usermode Container Sensor", "platform": "linux", "os": "Container", "os_version") I'm using a GKE kubernetes cluster . Can't start the container . deamon set stops at the init container : /bin/sh not found. (only bin/bash available on the container) If I edit the demon set it continue to fail because touch is missing . if I replace the command touch by $null >> in the deamon set .. I get a not authorized error
> 
> help will be appreciated

Bruh, that init container don't have privileged when create that empty file filestore

**Comment by redhatrises** [comment]
@ardimaul You are trying to use the Falcon Container sensor for the Kubernetes nodes, and Falcon Container sensor was not designed for this implementation. Please see https://github.com/CrowdStrike/falcon-helm/issues/79#issuecomment-955056938
