### ISSUE TITLE
Container with a sensitive volume mount detected

### ISSUE THREAD

**Issue by guojian83** [CrowdStrike/falcon-helm#81]
Hi,

This alert pops up in Azure Security Center after the sensor's deployment via the helm chart.
_Container with a sensitive volume mount detected_
_Sensitive mount path: /etc_
Just wonder if /etc is a must here?

Regards,
Jian

**Comment by redhatrises** [comment]
Currently, yes. /etc is a must here. This might change in the future but don't have timelines or if it will.

**Comment by guojian83** [comment]
Thanks.
