### ISSUE TITLE
Bug? When using node.enabled = true no Host / CVE telemetry is output to the Falcon console

### ISSUE THREAD

**Issue by nullify005** [CrowdStrike/falcon-helm#90]
Problem:

Using the helm chart deployment method with node.enabled = true there is no Host / CVE telemetry visible in the Falcon console despite the hosts having known vulnerabilities.

There is Container telemetry though.

Expected Behaviour:

CrowdStrike TAM insists that a "normal" install of the Linux agent will result in both Container & Host telemetry.

When I install via helm with node.enabled I expect to see both.

I understand that using the sidecar pattern I wouldn't, but I'm not using that at all.

Background:

We use kops to manage our k8s clusters which is currently using an Ubuntu 20 base.
With the helm install method on these hosts with the correct kernel versions etc. what we see is that there's no CVE telemetry collected for the hosts at all.
While we do have the ability to install the Linux agent as part of user_data that's not very kubernetes at all.

Is this intended?

**Comment by redhatrises** [comment]
Hello.

Thanks for opening this issue. This repo isn't the place to discuss or query about sensor capabilities or falcon console with deployments.

In general, the Linux sensor as a daemonset is still in Beta with no official support and capabilities may or may not work until such time that it is fully supported. Please reach out to your account team, and if needed, they or your TAM can reach out to me internally for more info.
